# Generated by Django 3.2.7 on 2021-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='author_pics'),
        ),
    ]
